// Uso: npm run test:db   (desde Frontend-HayCancha)
// Réplica LOCAL (en memoria) de la base de GridPlay + pruebas de la migración de seguridad.
// No se conecta a internet ni a Supabase.
import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const DIR_MIGRACIONES = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../migrations');
const db = new PGlite();

const U = {
  cliente: 'd0dcb3c7-5337-4359-b71a-3097ef722e0d',
  sani: '9b8faa16-f603-4656-9aea-7323ac9db349',
  sport: 'caba02f9-3a7c-4ad1-827e-61ca90b7af35',
  dueno: '4f339a7e-8dde-43b2-8516-c15b15f368dc',
};
const CLUB_SPORT = '990ba36d-ca0b-4319-9034-5f3c44e93930';
const CLUB_SANI = '01e5450b-590c-487e-918e-4b9664f681de';
const C67 = 'c0f784e9-fb3b-4307-996d-4808024b4645';
const C_SPORT_FUTBOL = '4f1a1b8c-7e00-4b22-8f34-ef652d2e8dc9';
const C_SANI2 = '921d0c52-d3a3-4912-95e0-0101f8514cc2';

// ---------- 1. Réplica del estado ACTUAL de producción (leído con el MCP en modo lectura) ----------
await db.exec(`
create role anon nologin; create role authenticated nologin; create role service_role nologin bypassrls;
create schema auth; create schema extensions; create schema storage;
grant usage on schema public, auth, extensions, storage to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;

create table auth.users (id uuid primary key default gen_random_uuid(), email text, raw_user_meta_data jsonb default '{}', aud text, role text, email_confirmed_at timestamptz default now());
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'sub', '')::uuid $$;
grant select on auth.users to authenticated;  -- (para las FK)
create function extensions.uuid_generate_v4() returns uuid language sql as $$ select gen_random_uuid() $$;

create table storage.buckets (id text primary key, name text, public boolean default false, file_size_limit bigint, allowed_mime_types text[]);
create table storage.objects (id uuid primary key default gen_random_uuid(), bucket_id text, name text, owner_id text);
create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name, '/') $$;
alter table storage.objects enable row level security;
grant all on storage.objects, storage.buckets to anon, authenticated;
create policy "Permitir todo 1ktc4f5_0" on storage.objects for select to public using (bucket_id = 'imagenes');
create policy "Permitir todo 1ktc4f5_1" on storage.objects for insert to public with check (bucket_id = 'imagenes');
create policy "Permitir todo 1ktc4f5_2" on storage.objects for update to public using (bucket_id = 'imagenes');
create policy "Permitir todo 1ktc4f5_3" on storage.objects for delete to public using (bucket_id = 'imagenes');
insert into storage.buckets (id, name, public) values ('imagenes', 'imagenes', true);

create table public.usuarios (id uuid primary key references auth.users(id), nombre_completo varchar not null, telefono varchar, rol varchar default 'cliente', strikes int default 0);
create table public.clubes (id uuid primary key default extensions.uuid_generate_v4(), nombre varchar not null, direccion varchar, telefono_contacto varchar, admin_id uuid not null references public.usuarios(id), imagen_url text, estacionamiento boolean default true, admin_email text, provincia text, ciudad text, descripcion text, color_primario text default '#0f172a', deporte text, techada boolean, cantidad_jugadores bigint default 5, precio_hora numeric, servicios text, correo_contacto text, redes_sociales jsonb default '{}', fotos_club text);
create table public.canchas (id uuid primary key default extensions.uuid_generate_v4(), club_id uuid references public.clubes(id), nombre varchar not null, deporte varchar not null, precio_hora numeric not null, activa boolean default true, hora_apertura time, hora_cierre time, imagen_url text, cantidad_jugadores bigint default 5, techada boolean);
create table public.reservas (id uuid primary key default extensions.uuid_generate_v4(), cancha_id uuid not null references public.canchas(id), usuario_id uuid not null references public.usuarios(id), fecha_hora_inicio timestamptz not null, fecha_hora_fin timestamptz not null, estado varchar default 'pendiente', precio_total numeric not null);
create table public.turnos (id bigint generated by default as identity primary key, cancha_id uuid, fecha date, hora_inicio text, nombre_cliente text, telefono_cliente text, horarios_disponibles text, extras jsonb);
create table public.productos (id bigint generated by default as identity primary key, nombre text, precio numeric, activo boolean, club_id uuid);
create table public.kiosco (id bigint generated by default as identity primary key, club_id uuid references public.clubes(id), nombre text not null, precio numeric not null, icono text, created_at timestamptz default now());

insert into auth.users (id, email, raw_user_meta_data) values
 ('${U.cliente}','laura@test.com','{"rol":"cliente"}'), ('${U.sani}','sani@gmail.com','{}'), ('${U.sport}','sport@gmail.com','{}'),
 ('${U.dueno}','facuimhoff2112@gmail.com','{}'), (gen_random_uuid(),'otro@test.com','{}');
insert into public.usuarios (id, nombre_completo, telefono, rol) values ('${U.dueno}','Facundo Imhoff','3564609641','DUEÑO DEL PROYECTO');
insert into public.clubes (id, nombre, admin_id, admin_email, provincia, ciudad) values
 ('${CLUB_SPORT}','SPORT AUTOMOVIL CLUB','${U.dueno}','sport@gmail.com','Córdoba','San Francisco'),
 ('${CLUB_SANI}','SANI','${U.dueno}','sani@gmail.com','Córdoba','San Francisco');
insert into public.canchas (id, club_id, nombre, deporte, precio_hora, hora_apertura, hora_cierre) values
 ('${C_SPORT_FUTBOL}','${CLUB_SPORT}','Cancha sport futbol','Fútbol',5000,null,null),
 ('${C_SANI2}','${CLUB_SANI}','Cancha Sani 2','Fútbol',60000,'16:00','23:00'),
 ('${C67}','${CLUB_SANI}','Cancha 67','Fútbol',67000,'08:00','23:00');
insert into public.turnos (cancha_id, fecha, hora_inicio, nombre_cliente, telefono_cliente) values
 ('${C67}','2026-07-15','17:00','Juan','1122334455'), ('${C_SANI2}','2026-07-15','17:00','Bloqueo por: x','BLOQUEO'),
 ('${C_SANI2}','2026-07-16','16:00','Ana','666'), ('${C_SANI2}','2026-07-16','18:00','Beto','111');
insert into public.productos (nombre, precio, activo, club_id) values ('COCA-COLA 1.5 Lts',6000,null,'${CLUB_SANI}'),('SPRITE',3000,null,'${CLUB_SANI}');
`);

// ---------- helpers de prueba ----------
const resultados = [];
const ok = (nombre, cond, detalle = '') => { resultados.push({ nombre, ok: !!cond, detalle }); };
const como = async (rol, uid) => {
  await db.exec(`reset role; select set_config('request.jwt.claims', '${uid ? JSON.stringify({ sub: uid, role: rol }) : '{}'}', false); set role ${rol};`);
};
const raiz = () => db.exec('reset role');
const intenta = async (sql, params) => { try { const r = await db.query(sql, params); return { r }; } catch (e) { return { e: e.message }; } };
const hoy = new Date(); const sumar = (d) => { const x = new Date(hoy); x.setDate(x.getDate() + d); return x.toISOString().slice(0, 10); };

// ---------- 2. ANTES de la migración: confirmar que la base está abierta ----------
await como('anon');
let a = await intenta('select count(*)::int n from public.turnos');
ok('ANTES: anónimo puede leer turnos (base abierta)', a.r?.rows[0].n === 4, `ve ${a.r?.rows[0].n} turnos`);
a = await intenta("delete from public.turnos where id = 1");
ok('ANTES: anónimo puede BORRAR turnos', !a.e);
await raiz();
await db.exec("insert into public.turnos (id, cancha_id, fecha, hora_inicio, nombre_cliente, telefono_cliente) overriding system value values (1,'" + C67 + "','2026-07-15','17:00','Juan','1122334455') on conflict do nothing");

// ---------- 3. Aplicar la migración ----------
try {
  // Se aplican TODAS las migraciones en orden, igual que en producción
  for (const archivo of fs.readdirSync(DIR_MIGRACIONES).filter((f) => f.endsWith('.sql')).sort()) {
    await db.exec(fs.readFileSync(path.join(DIR_MIGRACIONES, archivo), 'utf8'));
  }
  ok('Las migraciones se aplican sin errores', true);
} catch (e) {
  ok('Las migraciones se aplican sin errores', false, e.message);
  console.log(JSON.stringify(resultados, null, 1));
  process.exit(1);
}

// ---------- 4. Estado tras la migración (como administrador de la base) ----------
await raiz();
const admins = (await db.query('select c.nombre, u.email from public.clubes c join auth.users u on u.id = c.admin_id order by 1')).rows;
ok('Los clubes quedan asignados a sus admins reales', admins.length === 2 && admins.find(x => x.nombre === 'SANI')?.email === 'sani@gmail.com' && admins.find(x => x.nombre.startsWith('SPORT'))?.email === 'sport@gmail.com', JSON.stringify(admins));
const roles = Object.fromEntries((await db.query('select id, rol from public.usuarios')).rows.map(r => [r.id, r.rol]));
ok('Todas las cuentas tienen perfil', Object.keys(roles).length === 5);
ok('sani y sport son admin, dueño superadmin, resto cliente', roles[U.sani] === 'admin' && roles[U.sport] === 'admin' && roles[U.dueno] === 'superadmin' && roles[U.cliente] === 'cliente');
ok('Se eliminó la columna admin_email', (await db.query("select count(*)::int n from information_schema.columns where table_name='clubes' and column_name='admin_email'")).rows[0].n === 0);
ok('Turnos viejos conservan precio congelado (y el bloqueo no)', JSON.stringify((await db.query('select precio_final::float from public.turnos order by id')).rows.map(r => r.precio_final)) === '[67000,null,60000,60000]');

// nueva cuenta por el trigger: el rol siempre es cliente aunque la metadata diga admin
const nuevo = 'aaaaaaaa-0000-0000-0000-000000000001';
await db.query(`insert into auth.users (id, email, raw_user_meta_data) values ('${nuevo}','hack@test.com','{"rol":"admin","full_name":"Hacker"}')`);
const p = (await db.query(`select rol, nombre_completo from public.usuarios where id='${nuevo}'`)).rows[0];
ok('Alta nueva: rol cliente aunque la metadata diga "admin"', p?.rol === 'cliente' && p?.nombre_completo === 'Hacker', JSON.stringify(p));

// ---------- 5. Anónimo (cualquiera con la clave pública) ----------
await como('anon');
a = await intenta('select count(*)::int n from public.clubes'); ok('Anónimo ve los clubes (público)', a.r?.rows[0].n === 2);
a = await intenta('select count(*)::int n from public.canchas'); ok('Anónimo ve las canchas (público)', a.r?.rows[0].n === 3);
a = await intenta('select count(*)::int n from public.productos'); ok('Anónimo ve los productos activos', a.r?.rows[0].n === 2);
a = await intenta('select * from public.turnos'); ok('Anónimo NO puede leer turnos', !!a.e, a.e);
a = await intenta('select * from public.usuarios'); ok('Anónimo NO puede leer usuarios', !!a.e, a.e);
a = await intenta('select * from public.reservas'); ok('Anónimo NO puede leer la tabla legacy', !!a.e, a.e);
a = await intenta('select * from public.suscripciones'); ok('Anónimo NO puede leer suscripciones', !!a.e, a.e);
a = await intenta('delete from public.turnos'); ok('Anónimo NO puede borrar turnos', !!a.e, a.e);
a = await intenta("update public.clubes set nombre='hack'"); ok('Anónimo NO puede editar clubes', !!a.e, a.e);
a = await intenta("insert into public.clubes (nombre, admin_id) values ('x', '" + U.dueno + "')"); ok('Anónimo NO puede crear clubes', !!a.e, a.e);
a = await intenta(`select public.crear_reserva('${C67}', '${sumar(1)}', '10:00', 'Anon', '3564000000')`); ok('Anónimo NO puede reservar', !!a.e, a.e);
a = await intenta(`select public.registrar_club('x','','a','b','c','3564000000',true,'','{}','','a@b.com')`); ok('Anónimo NO puede registrar club', !!a.e, a.e);
a = await intenta(`select count(*)::int n from public.disponibilidad_cancha('${C_SANI2}', '2026-07-01', '2026-07-31')`);
ok('Anónimo ve solo la disponibilidad (slots ocupados)', a.r?.rows[0].n === 3, `${a.r?.rows[0].n} slots`);
a = await intenta(`select * from public.disponibilidad_cancha('${C_SANI2}', '2026-07-01', '2026-07-31') limit 1`);
ok('La disponibilidad no expone nombres ni teléfonos', a.r && Object.keys(a.r.rows[0]).join() === 'fecha,hora_inicio', Object.keys(a.r?.rows[0] || {}).join());
a = await intenta("insert into storage.objects (bucket_id, name) values ('imagenes','x/y.png')"); ok('Anónimo NO puede subir archivos', !!a.e, a.e);

// ---------- 6. Jugador (cliente logueado) ----------
await como('authenticated', U.cliente);
a = await intenta(`select public.crear_reserva('${C67}', '${sumar(1)}', '10:00', 'Laura Test', '3564123456', '[{"id":1,"cantidad":2,"precio_unitario":1}]'::jsonb) id`);
ok('Jugador puede reservar', !a.e, a.e);
const idRes = a.r?.rows[0].id;
a = await intenta(`select precio_final::float pf, extras, usuario_id from public.turnos where id = ${idRes}`);
const t = a.r?.rows[0];
ok('El precio sale del servidor (67000), no del cliente', t?.pf === 67000, `precio_final=${t?.pf}`);
ok('El extra se recalcula en servidor (2 x 6000 = 12000)', t?.extras?.[0]?.subtotal === 12000 && t?.extras?.[0]?.precio_unitario === 6000, JSON.stringify(t?.extras));
ok('La reserva queda a nombre del jugador', t?.usuario_id === U.cliente);
a = await intenta(`select public.crear_reserva('${C67}', '${sumar(1)}', '10:00', 'Otro', '3564123456')`); ok('No se puede reservar un horario ocupado', a.e?.includes('SLOT_OCUPADO'), a.e);
a = await intenta(`select public.crear_reserva('${C67}', '${sumar(1)}', '11:00', 'Otro', '3564123456', '[{"id":999,"cantidad":1}]'::jsonb)`); ok('Producto inexistente rechazado', a.e?.includes('EXTRAS_INVALIDOS'), a.e);
a = await intenta(`select public.crear_reserva('${C67}', '${sumar(-3)}', '11:00', 'Otro', '3564123456')`); ok('Fecha pasada rechazada', a.e?.includes('FECHA_INVALIDA'), a.e);
a = await intenta(`select public.crear_reserva('${C67}', '${sumar(1)}', '03:00', 'Otro', '3564123456')`); ok('Fuera del horario de la cancha rechazado', a.e?.includes('FUERA_DE_HORARIO'), a.e);
a = await intenta(`select public.crear_reserva('${C67}', '${sumar(1)}', '12:00', 'Otro', 'BLOQUEO')`); ok('Teléfono "BLOQUEO" rechazado', a.e?.includes('TELEFONO_INVALIDO'), a.e);
a = await intenta(`select public.crear_reserva('${C67}', '${sumar(1)}', '12:30', 'Otro', '3564123456')`); ok('Hora que no es en punto rechazada', a.e?.includes('HORA_INVALIDA'), a.e);
a = await intenta('select count(*)::int n from public.turnos'); ok('El jugador ve SOLO su turno (no los ajenos)', a.r?.rows[0].n === 1, `ve ${a.r?.rows[0].n}`);
a = await intenta(`update public.usuarios set rol='admin' where id='${U.cliente}'`); ok('El jugador NO puede volverse admin editando su perfil', !!a.e, a.e);
a = await intenta(`update public.usuarios set nombre_completo='Laura Nueva' where id='${U.cliente}'`); ok('El jugador SÍ puede cambiar su nombre', !a.e && a.r?.affectedRows === 1, a.e);
a = await intenta(`insert into public.turnos (cancha_id, fecha, hora_inicio, nombre_cliente, telefono_cliente) values ('${C67}', '${sumar(2)}', '10:00', 'x', '111111')`); ok('El jugador NO puede insertar turnos directo', !!a.e, a.e);
a = await intenta('delete from public.turnos where id = 1'); ok('El jugador NO puede borrar turnos ajenos', a.r?.affectedRows === 0, `borró ${a.r?.affectedRows}`);
a = await intenta("update public.canchas set nombre='hack'"); ok('El jugador NO puede editar canchas', a.r?.affectedRows === 0);
a = await intenta("update public.clubes set nombre='hack'"); ok('El jugador NO puede editar clubes', a.r?.affectedRows === 0);
a = await intenta('select count(*)::int n from public.usuarios'); ok('El jugador ve solo su propio perfil', a.r?.rows[0].n === 1);
a = await intenta(`update public.clubes set admin_id='${U.cliente}' where id='${CLUB_SANI}'`); ok('El jugador NO puede robar un club', !!a.e || a.r?.affectedRows === 0);
a = await intenta("insert into storage.objects (bucket_id, name, owner_id) values ('imagenes','otra-persona/x.png','" + U.cliente + "')"); ok('El jugador NO puede subir archivos a la carpeta de otro', !!a.e, a.e);
a = await intenta("insert into storage.objects (bucket_id, name, owner_id) values ('imagenes','" + U.cliente + "/logos/x.png','" + U.cliente + "')"); ok('El jugador SÍ puede subir a su propia carpeta', !a.e, a.e);
a = await intenta(`delete from public.turnos where id = ${idRes} returning id`); ok('El jugador SÍ puede cancelar su reserva futura', a.r?.rows.length === 1, a.e);

// ---------- 7. Se vuelve admin por el camino oficial ----------
await como('authenticated', U.cliente);
a = await intenta(`select public.registrar_club('Club Test','desc','Córdoba','San Francisco','Calle 1','3564000000',true,'Parrilla','{}','','a@b.com')`);
ok('SIN suscripción activa no se puede registrar un club', a.e?.includes('SUSCRIPCION_REQUERIDA'), a.e);
a = await intenta(`insert into public.suscripciones (user_id, plan, estado) values ('${U.cliente}','Full','activa')`);
ok('El jugador NO puede activarse una suscripción a sí mismo', !!a.e, a.e);
a = await intenta(`update public.suscripciones set estado = 'activa'`);
ok('Nadie puede editar suscripciones desde el cliente', !!a.e, a.e);
a = await intenta('select count(*)::int n from public.suscripciones');
ok('El jugador no ve suscripciones (solo las propias, y no tiene)', a.r?.rows[0].n === 0);
// El backend (service_role, verificó el pago contra Mercado Pago) registra la suscripción:
await raiz();
await db.query(`insert into public.suscripciones (user_id, mp_preapproval_id, plan, estado, monto) values ('${U.cliente}', 'mp-123', 'Full', 'activa', 50000)`);
a = await intenta(`insert into public.suscripciones (user_id, mp_preapproval_id, plan, estado) values ('${U.sani}', 'mp-123', 'Full', 'activa')`);
ok('Una misma suscripción de Mercado Pago no puede reclamarse dos veces', !!a.e, a.e);
await como('authenticated', U.cliente);
a = await intenta('select count(*)::int n from public.suscripciones');
ok('Con suscripción activa, el jugador ve la suya', a.r?.rows[0].n === 1);
a = await intenta(`select public.registrar_club('Club Test','desc','Córdoba','San Francisco','Calle 1','3564000000',true,'Parrilla','{"instagram":"@x"}','https://x/y.png','a@b.com') id`);
ok('registrar_club crea el club', !a.e, a.e);
a = await intenta(`select public.registrar_club('Club 2','','a','b','c','3564000000',true,'','{}','','a@b.com')`); ok('No puede registrar un segundo club', a.e?.includes('CLUB_EXISTENTE'), a.e);
await raiz();
ok('Tras registrar el club, el rol pasa a admin (lo fija el servidor)', (await db.query(`select rol from public.usuarios where id='${U.cliente}'`)).rows[0].rol === 'admin');

// ---------- 8. Admin SANI ----------
await como('authenticated', U.sani);
a = await intenta('select count(*)::int n from public.turnos'); ok('Admin Sani ve los turnos de SU club (los 4 viejos)', a.r?.rows[0].n === 4, `ve ${a.r?.rows[0].n}`);
a = await intenta(`insert into public.turnos (cancha_id, fecha, hora_inicio, nombre_cliente, telefono_cliente) values ('${C67}', '${sumar(3)}', '15:00', 'Manual', '3564999999') returning precio_final::float pf`);
ok('Admin puede cargar un turno manual y toma el precio de la cancha', a.r?.rows[0].pf === 67000, a.e);
a = await intenta(`insert into public.turnos (cancha_id, fecha, hora_inicio, nombre_cliente, telefono_cliente) values ('${C67}', '${sumar(3)}', '16:00', 'Bloqueo', 'BLOQUEO') returning precio_final`);
ok('Un bloqueo no factura (precio nulo)', a.r?.rows[0].precio_final === null, a.e);
a = await intenta(`insert into public.turnos (cancha_id, fecha, hora_inicio, nombre_cliente, telefono_cliente) values ('${C67}', '${sumar(3)}', '15:00', 'Dup', '3564999999')`); ok('Admin NO puede duplicar un horario', !!a.e, a.e);
a = await intenta(`insert into public.turnos (cancha_id, fecha, hora_inicio, nombre_cliente, telefono_cliente) values ('${C_SPORT_FUTBOL}', '${sumar(3)}', '10:00', 'x', '111111')`); ok('Admin Sani NO puede cargar turnos en canchas de OTRO club', !!a.e, a.e);
a = await intenta(`update public.canchas set nombre = nombre where club_id = '${CLUB_SPORT}'`); ok('Admin Sani NO puede editar canchas de Sport', a.r?.affectedRows === 0);
a = await intenta(`update public.clubes set nombre = nombre where id = '${CLUB_SPORT}'`); ok('Admin Sani NO puede editar el club de Sport', a.r?.affectedRows === 0);
a = await intenta(`update public.clubes set admin_id = '${U.sport}' where id = '${CLUB_SANI}'`); ok('Admin Sani NO puede ceder/cambiar el dueño del club', !!a.e, a.e);
a = await intenta(`update public.clubes set descripcion = 'Nueva' where id = '${CLUB_SANI}'`); ok('Admin Sani SÍ edita su propio club', a.r?.affectedRows === 1, a.e);
a = await intenta(`update public.canchas set superficie = 'Cemento' where id = '${C67}'`); ok('Admin Sani SÍ edita su cancha (columna superficie nueva)', a.r?.affectedRows === 1, a.e);
a = await intenta(`insert into public.canchas (club_id, nombre, deporte, precio_hora) values ('${CLUB_SPORT}', 'x', 'Pádel', 1)`); ok('Admin Sani NO puede crear canchas en otro club', !!a.e, a.e);
a = await intenta(`insert into public.productos (club_id, nombre, precio) values ('${CLUB_SANI}', 'Agua', 1500) returning activo`); ok('Admin crea productos (activo por defecto)', a.r?.rows[0].activo === true, a.e);
a = await intenta(`insert into public.productos (club_id, nombre, precio) values ('${CLUB_SPORT}', 'Agua', 1500)`); ok('Admin Sani NO crea productos en otro club', !!a.e, a.e);
a = await intenta(`delete from public.turnos where cancha_id = '${C67}' and hora_inicio = '16:00' and fecha = '${sumar(3)}' returning id`); ok('Admin puede liberar un bloqueo', a.r?.rows.length === 1, a.e);

await como('authenticated', U.sani);
a = await intenta("select estado, plan from public.suscripciones");
ok('Los clubes existentes quedaron con suscripción activa (legado) y ven solo la suya', a.r?.rows.length === 1 && a.r.rows[0].estado === 'activa' && a.r.rows[0].plan === 'legado', JSON.stringify(a.r?.rows));

// ---------- 9. Admin SPORT ----------
await como('authenticated', U.sport);
a = await intenta('select count(*)::int n from public.turnos'); ok('Admin Sport NO ve turnos de Sani', a.r?.rows[0].n === 0, `ve ${a.r?.rows[0].n}`);

// ---------- 10. Límite anti-acaparamiento ----------
await como('authenticated', U.dueno);
let bloqueado = false;
for (let i = 0; i < 12; i++) {
  const d = sumar(1 + Math.floor(i / 5)); const h = String(9 + (i % 5)).padStart(2, '0') + ':00';
  const r = await intenta(`select public.crear_reserva('${C67}', '${d}', '${h}', 'Dueno', '3564000000')`);
  if (r.e?.includes('LIMITE_RESERVAS')) { bloqueado = i >= 10; break; }
}
ok('Un jugador no puede acaparar más de 10 reservas futuras', bloqueado);

// ---------- 11. Bucket ----------
await raiz();
const b = (await db.query("select file_size_limit::int l, allowed_mime_types m from storage.buckets where id='imagenes'")).rows[0];
ok('El bucket queda limitado a imágenes ≤ 5 MB', b.l === 5242880 && b.m.join() === 'image/jpeg,image/png,image/webp', JSON.stringify(b));

// ---------- Resumen ----------
const fallos = resultados.filter(r => !r.ok);
for (const r of resultados) console.log((r.ok ? 'OK   ' : 'FALLA') + ' ' + r.nombre + (r.ok || !r.detalle ? '' : '  -> ' + r.detalle));
console.log(`\n${resultados.length - fallos.length}/${resultados.length} pruebas correctas`);
process.exit(fallos.length ? 1 : 0);
